source/jupyter/index.rst

Replace valohai/jupyhai with valohai/mnist_notebook example

---

source/core-concepts/executions.rst
source/core-concepts/what-is-valohai.rst

Some touchups

---

requirements.in
requirements.txt

They merged our changes and made a release.

Switch back to sphinx-sitemap main branch

---

requirements.in
requirements.txt
source/_themes/valodoc/static_src/_cli_documentation.scss
source/_themes/valodoc/static_src/valodoc.scss
source/conf.py
source/valohai-cli/index.rst
source/valohai-cli/reference/environments.rst
source/valohai-cli/reference/execution.rst
source/valohai-cli/reference/index.rst
source/valohai-cli/reference/init.rst
source/valohai-cli/reference/lint.rst
source/valohai-cli/reference/login.rst
source/valohai-cli/reference/logout.rst
source/valohai-cli/reference/parcel.rst
source/valohai-cli/reference/project.rst
source/valohai-cli/reference/update-check.rst

Add valohai-cli reference generation

---

source/valohai-yaml/step-environment-variables.rst

Document special environment variables

---

source/guides/airflow-management/index.rst

Feel free to edit the text as you feel appropriate.

Link to Airflow article and git repo

---

source/core-concepts/index.rst
source/core-concepts/notebooks.rst

Add stub documentation for notebooks

---

source/_themes/valodoc/layout.html
source/_themes/valodoc/static_src/_knowledgebase.scss
source/tutorials/valohai/advanced/index.rst
source/tutorials/valohai/index.rst

* Fixed the search functionality (newer version of jQuery was messing it up)
* Added details on how to parse parameters with argparse
* Fixed some linking between new Valohai tutorials
* Small adjustment on searchbox formating

Fixed search & updated some tutorials

---

source/core-concepts/parameters.rst
source/core-concepts/pipelines.rst
source/executions/metadata/index.rst
source/index.rst
source/tutorials/accessing-repositories-during-executions/index.rst
source/tutorials/apis/_useAPIsbasic.rst
source/tutorials/apis/downloadMetadata.rst
source/tutorials/apis/fetchFailedExecutions.rst
source/tutorials/apis/fetchProjects.rst
source/tutorials/apis/index.rst
source/tutorials/apis/triggerExecFromGitHub.rst
source/tutorials/index.rst
source/tutorials/valohai/advanced/index.rst
source/valohai-api/index.rst

* Updated new tutorials for working with Valohai APIs
* Tutorials based on customer requests (ssh into another repo from inside an execution & trigger automatic executions from GitHub Actions)
* Cross-references tutorials in the relevant places in docs
* Updated front page to include API as core concepts
* Included YouTube getting started videos on index

Tutorial refresh

---

source/valohai-yaml/endpoint/index.rst

Correct SCRIPT_NAME docs to reflect current reality

---

source/valohai-yaml/step-inputs.rst

Updated step.inputs to include instructions for KeepDirectories and filename

KeepDirectories and filename addition

---

source/core-concepts/data-stores.rst

Updated with @ruksi's notes about data versioning. Putting to docs so it's easier to reference to in future converstions

Updated with notes about data versioning

---

source/_templates/base.html
source/_templates/page.html
source/howto/setup/gcp_private_worker.rst

- Keep track of page visits etc.
- Collect feedback with "was this page useful"

Added Google analytics

---

source/tutorials/example-project/quick-start-r.rst
source/tutorials/quickstart/index.rst

Added information about using other languages than Python to the starting page of 101 tutorial.

Add Python disclaimer to 101 tutorials starting page.

---

source/howto/pipelines/index.rst
source/howto/pipelines/pipeline-utils.rst

Added instructions how to use valohai-utils for creating pipelines from the CLI.

Add how to create pipelines with utils

---

source/topic-guides/core-concepts/pipelines.rst
source/topic-guides/executions/metadata/index.rst
source/tutorials/quickstart/quickstart-pipeline.rst

These are now under Valohai 101 -> Create pipeline. Might make sense to reorganize to make the docs more clear.

Add sections about pipeline conditions and parameter edges

---

source/reference-guides/valohai-cli/execution.rst
source/reference-guides/valohai-yaml/pipeline/edges/index.rst
source/reference-guides/valohai-yaml/step-parameters.rst
source/tutorials/quickstart/quickstart-pipeline.rst

Added instructions for parameter choices, metadata source and fixed a couple of small things.

Add instructions for parameter choices

---

source/howto/setup/deployment/aws-eks-cluster.rst

* Include autoscaler setup
* Additional IAMs
* Skip nginx

Updated EKS instructions

---

source/_redirects/__init__.py
source/howto/setup/aws_hybrid.rst
source/howto/setup/azure_hybrid.rst
source/howto/setup/gcp_hybrid.rst

Private worker update

---

source/howto/setup/gcp/manual.rst
source/howto/setup/onpremises/index.rst
source/howto/setup/self-hosted/index.rst

- Mention Git and Docker Registry as requirements for the self-hosted install
- FAQ for onprem workers
- Linux requirement for on-premise machines

Selfhosted

---

source/topic-guides/executions/file-config/index.rst

Added the new items to `execution.json` and `execution.yaml`. Made also the values more general than they what they were.

Add new config items

---

source/howto/new-user-guide/code/data.rst
source/howto/new-user-guide/code/metadata.rst
source/howto/new-user-guide/code/parameters.rst
source/howto/new-user-guide/index.rst
source/howto/new-user-guide/yaml.rst

Added a Friday video extravaganza.

Add bring your project to Valohai videos

---

source/howto/remote-access/index.rst
source/howto/remote-access/pycharm.rst
source/howto/remote-access/vscode.rst

Tutorials for general connection + VSCode and PyCharm debugging.

Add tutorial videos for remote access

---

source/tutorials/apis/download-metadata.rst
source/tutorials/apis/fetch-failed-executions.rst
source/tutorials/apis/fetch-projects.rst
source/tutorials/apis/trigger-exec-from-github.rst

Updated the API token handling and added the video. I will update the help also once this is reviewed.

Api tutorial videos
